/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Controller;
import Model.Clases.Producto;
import java.util.Calendar;
import java.util.List;
import javax.swing.JTable;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USUARIO
 */
public class View extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public View() {
        initComponents();
        uptadeTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneRegister = new javax.swing.JTabbedPane();
        jPanelRegister = new javax.swing.JPanel();
        jTextFieldP1Name = new javax.swing.JTextField();
        jTextFieldP1Amount = new javax.swing.JTextField();
        jTextFieldP1Price = new javax.swing.JTextField();
        jComboBoxP1Category = new javax.swing.JComboBox<>();
        jLabel1P1Name = new javax.swing.JLabel();
        jLabelP1Amount = new javax.swing.JLabel();
        jLabelP1Price = new javax.swing.JLabel();
        jLabelP1Category = new javax.swing.JLabel();
        jButtonP1Save = new javax.swing.JButton();
        jLabelWaringp1 = new javax.swing.JLabel();
        jPanelConsult = new javax.swing.JPanel();
        jButtonDelete = new javax.swing.JButton();
        jButtonSearch = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        JTextId = new javax.swing.JTextField();
        JTextName = new javax.swing.JTextField();
        JTextAmount = new javax.swing.JTextField();
        LabelID = new javax.swing.JLabel();
        LabelName = new javax.swing.JLabel();
        jLabelAmount = new javax.swing.JLabel();
        jTextPrice = new javax.swing.JTextField();
        jLabelPrice = new javax.swing.JLabel();
        jComboBoxCategory = new javax.swing.JComboBox<>();
        jLabelCategory = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTable = new javax.swing.JTable();
        jLabelWaring = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextFieldP1Name.setToolTipText("");

        jComboBoxP1Category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ASEO", "VIVERES" }));

        jLabel1P1Name.setText("Nombre");

        jLabelP1Amount.setText("Cantidad");

        jLabelP1Price.setText("Precio");

        jLabelP1Category.setText("Categoria");

        jButtonP1Save.setText("Guardar");
        jButtonP1Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonP1SaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelRegisterLayout = new javax.swing.GroupLayout(jPanelRegister);
        jPanelRegister.setLayout(jPanelRegisterLayout);
        jPanelRegisterLayout.setHorizontalGroup(
            jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRegisterLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonP1Save)
                .addGap(60, 60, 60))
            .addGroup(jPanelRegisterLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelWaringp1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelRegisterLayout.createSequentialGroup()
                        .addGroup(jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1P1Name)
                            .addComponent(jLabelP1Amount)
                            .addComponent(jLabelP1Price)
                            .addComponent(jLabelP1Category))
                        .addGap(72, 72, 72)
                        .addGroup(jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldP1Name, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jComboBoxP1Category, javax.swing.GroupLayout.Alignment.LEADING, 0, 122, Short.MAX_VALUE)
                                .addComponent(jTextFieldP1Price, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldP1Amount, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(0, 402, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelRegisterLayout.setVerticalGroup(
            jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegisterLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldP1Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1P1Name))
                .addGap(18, 18, 18)
                .addGroup(jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldP1Amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelP1Amount))
                .addGap(18, 18, 18)
                .addGroup(jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldP1Price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelP1Price))
                .addGap(18, 18, 18)
                .addGroup(jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxP1Category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelP1Category))
                .addGap(54, 54, 54)
                .addComponent(jLabelWaringp1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 185, Short.MAX_VALUE)
                .addComponent(jButtonP1Save)
                .addGap(27, 27, 27))
        );

        jTabbedPaneRegister.addTab("Registrar", jPanelRegister);

        jButtonDelete.setText("Eliminar");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jButtonSearch.setText("Consultar");
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });

        jButtonUpdate.setText("Actualizar");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        LabelID.setText("ID");

        LabelName.setText("Nombre");

        jLabelAmount.setText("Cantidad");

        jLabelPrice.setText("Precio");

        jComboBoxCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ASEO", "VIVERES" }));

        jLabelCategory.setText("Categoria");

        jTableTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre", "Categoria", "Cantidad", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableTable);
        if (jTableTable.getColumnModel().getColumnCount() > 0) {
            jTableTable.getColumnModel().getColumn(0).setResizable(false);
            jTableTable.getColumnModel().getColumn(1).setResizable(false);
            jTableTable.getColumnModel().getColumn(2).setResizable(false);
            jTableTable.getColumnModel().getColumn(3).setResizable(false);
            jTableTable.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout jPanelConsultLayout = new javax.swing.GroupLayout(jPanelConsult);
        jPanelConsult.setLayout(jPanelConsultLayout);
        jPanelConsultLayout.setHorizontalGroup(
            jPanelConsultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConsultLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelConsultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelWaring, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelConsultLayout.createSequentialGroup()
                        .addGroup(jPanelConsultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelName)
                            .addComponent(LabelID)
                            .addComponent(jLabelAmount)
                            .addComponent(jLabelPrice)
                            .addComponent(jLabelCategory))
                        .addGap(52, 52, 52)
                        .addGroup(jPanelConsultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelConsultLayout.createSequentialGroup()
                                .addGroup(jPanelConsultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextPrice)
                                    .addComponent(JTextId)
                                    .addComponent(JTextName)
                                    .addComponent(JTextAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(63, 63, 63)
                                .addGroup(jPanelConsultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonSearch)
                                    .addComponent(jButtonDelete)
                                    .addComponent(jButtonUpdate))))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanelConsultLayout.setVerticalGroup(
            jPanelConsultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConsultLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addGroup(jPanelConsultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDelete)
                    .addComponent(JTextId, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelConsultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTextName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSearch)
                    .addComponent(LabelName))
                .addGap(11, 11, 11)
                .addGroup(jPanelConsultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTextAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonUpdate)
                    .addComponent(jLabelAmount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelConsultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPrice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelConsultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCategory))
                .addGap(29, 29, 29)
                .addComponent(jLabelWaring)
                .addContainerGap())
        );

        jTabbedPaneRegister.addTab("Consultar", jPanelConsult);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneRegister)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneRegister, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonP1SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonP1SaveActionPerformed
        // TODO add your handling code here:
        String nombre = jTextFieldP1Name.getText();
        String cantidad = jTextFieldP1Amount.getText();
        String categoria =(String)jComboBoxP1Category.getSelectedItem();
        String precio= jTextFieldP1Price.getText();
        if(nombre.length()==0||cantidad.length()==0||precio.length()==0){
            timerTask("Han quedado campos vacios o ha ingresado datos erroneos.Corrijalos e intente de nuevo", "p1");
            //this.jLabelWaringp1.setText("Han quedado campos vacios o ha ingresado datos erroneos.Corrijalos e intente de nuevo");
        }else{
            try {        
                Controller.registrarProducto(nombre, Integer.valueOf(cantidad), categoria, Double.parseDouble(precio));
                timerTask("Registro exitoso", "p1");
                this.jLabelWaringp1.setText("");
                this.jTextFieldP1Name.setText("");
                this.jTextFieldP1Amount.setText("");
                this.jTextFieldP1Price.setText("");
                this.jComboBoxP1Category.setSelectedItem("ASEO");
                uptadeTable();    
            } 
            catch (Exception e) {
                timerTask("Han quedado campos vacios o ha ingresado datos erroneos.Corrijalos e intente de nuevo", "p1");
              //  this.jLabelWaringp1.setText("Han quedado campos vacios o ha ingresado datos erroneos.Corrijalos e intente de nuevo");
            }
        }

         
         
    }//GEN-LAST:event_jButtonP1SaveActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // TODO add your handling code here:
        String ID = this.JTextId.getText();
        
        if (ID.length() == 0 ) {
            timerTask("Ingrese un ID valido y vuelva a intentarlo", "p2");
            //this.jLabelWaring.setText("Ingrese un ID valido y vuelva a intentarlo");
        } else {
            Producto p = Controller.obtenerProducto(Integer.valueOf(ID));
            if (p!=null) {
                Controller.borrarProducto(Integer.valueOf(ID));
                timerTask("Eliminacion Exitosa", "p2");  
            } else {
                timerTask("El ID ingresado no existe", "p2");
            }              
            
           // this.jLabelWaring.setText("Eliminacion Exitosa");
            this.JTextId.setText("");
            this.JTextName.setText("");
            this.JTextAmount.setText("");
            this.jTextPrice.setText("");
            this.jComboBoxCategory.setSelectedItem("ASEO");
            uptadeTable();
        }
        
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
        // TODO add your handling code here:
        String id = this.JTextId.getText();
        DefaultTableModel modelo =(DefaultTableModel) this.jTableTable.getModel();
        modelo.setRowCount(0);
        if(id.length()==0){
            List<Producto> listaProductos = Controller.listarProductos();
            for (int i = 0; i < listaProductos.size() ; i++) {
                Producto p = listaProductos.get(i);
                modelo.insertRow(i, new Object[]{p.getId(),p.getNombre(),p.getCantidad(),p.getCategoria(),p.getPrecio()});                               
            }
        }else{
            int ID = Integer.valueOf(id);
            Producto p = Controller.obtenerProducto(ID);
            if (p!=null){
                modelo.insertRow(0, new Object[]{p.getId(),p.getNombre(),p.getCantidad(),p.getCategoria(),p.getPrecio()});
                }else{
                    timerTask("El ID ingresado no se encuentra registrado.", "p2");
                    uptadeTable();
                }
              
        }
            this.JTextId.setText("");
            this.JTextName.setText("");
            this.JTextAmount.setText("");
            this.jTextPrice.setText("");
            this.jComboBoxCategory.setSelectedItem("ASEO");
    }//GEN-LAST:event_jButtonSearchActionPerformed

    private void jTableTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTableMouseClicked
        // TODO add your handling code here:
        JTable table = (JTable) evt.getSource();
        int row = table.rowAtPoint(evt.getPoint());
        DefaultTableModel modelo =(DefaultTableModel) this.jTableTable.getModel();
        
        String id =String.valueOf(modelo.getValueAt(row, 0));
        String nombre = String.valueOf(modelo.getValueAt(row, 1));
        String cantidad= String.valueOf(modelo.getValueAt(row, 2));
        String categoria = String.valueOf(modelo.getValueAt(row, 3));
        String precio = String.valueOf(modelo.getValueAt(row, 4));
        
        this.JTextId.setText(id);
        this.JTextName.setText(nombre);
        this.JTextAmount.setText(cantidad);
        this.jComboBoxCategory.setSelectedItem(categoria);
        this.jTextPrice.setText(precio);
        
        
    }//GEN-LAST:event_jTableTableMouseClicked

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        // TODO add your handling code here:
        
        String Id = this.JTextId.getText();
        String nombre = this.JTextName.getText();
        String cantidad=this.JTextAmount.getText();
        String categoria=(String)this.jComboBoxCategory.getSelectedItem();
        String precio = this.jTextPrice.getText();
         
        if (Id.length()== 0 || nombre.length()==0 || cantidad.length()==0 || precio.length()==0) {
            timerTask("Han quedado campos vacios. Corrijalos e intente de nuevo", "p2");
          //  this.jLabelWaring.setText("Han quedado campos vacios. Corrijalos e intente de nuevo");
        }else{
            try {
            Controller.actualizarProducto(Integer.valueOf(Id), nombre, Integer.valueOf(cantidad), categoria, Double.valueOf(precio));
            this.JTextId.setText("");
            this.JTextName.setText("");
            this.JTextAmount.setText("");
            this.jTextPrice.setText("");
            this.jComboBoxCategory.setSelectedItem("ASEO");
            timerTask("Actualizacion Exitosa", "p2");
            } catch (Exception e) {
            timerTask("Ha ingresado datos erroneos. Corrijalos e intente de nuevo", "p2");
            }

        }
        uptadeTable();

    }//GEN-LAST:event_jButtonUpdateActionPerformed
    public void uptadeTable(){
        DefaultTableModel modelo =(DefaultTableModel) this.jTableTable.getModel();
        modelo.setRowCount(0);
        List<Producto> listaProductos = Controller.listarProductos();
        for (int i = 0; i < listaProductos.size() ; i++) {
            Producto p = listaProductos.get(i);
            modelo.insertRow(i, new Object[]{p.getId(),p.getNombre(),p.getCantidad(),p.getCategoria(),p.getPrecio()});              
        }
        
    }
    
    public void timerTask(String mensaje,String dato){
      
      Timer timer = new Timer();
      TimerTask task = new TimerTask() {
          int tic=1;
          @Override
          public void run() {
              
              if(tic==1){
                if(dato.equals("p1")){
                    jLabelWaringp1.setText(mensaje); 
                  }
                if(dato.equals("p2")){
                    jLabelWaring.setText(mensaje); 
                  }

              }else{
                  jLabelWaringp1.setText("");
                  jLabelWaring.setText("");
                  timer.cancel();
              }
            tic--;
          }
          
      };
      timer.schedule(task,0,3000);
        
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTextAmount;
    private javax.swing.JTextField JTextId;
    private javax.swing.JTextField JTextName;
    private javax.swing.JLabel LabelID;
    private javax.swing.JLabel LabelName;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonP1Save;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JComboBox<String> jComboBoxCategory;
    private javax.swing.JComboBox<String> jComboBoxP1Category;
    private javax.swing.JLabel jLabel1P1Name;
    private javax.swing.JLabel jLabelAmount;
    private javax.swing.JLabel jLabelCategory;
    private javax.swing.JLabel jLabelP1Amount;
    private javax.swing.JLabel jLabelP1Category;
    private javax.swing.JLabel jLabelP1Price;
    private javax.swing.JLabel jLabelPrice;
    private javax.swing.JLabel jLabelWaring;
    private javax.swing.JLabel jLabelWaringp1;
    private javax.swing.JPanel jPanelConsult;
    private javax.swing.JPanel jPanelRegister;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPaneRegister;
    private javax.swing.JTable jTableTable;
    private javax.swing.JTextField jTextFieldP1Amount;
    private javax.swing.JTextField jTextFieldP1Name;
    private javax.swing.JTextField jTextFieldP1Price;
    private javax.swing.JTextField jTextPrice;
    // End of variables declaration//GEN-END:variables
}
